Devcard3/DevCard_project2/Models/Article.cs
namespace DevCard_project2.Models
{
    public class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }

        public Article(long id, string title, string description, string image)
        {
            Id = id;
            Title = title;
            Description = description;
            Image = image;
        }
    }
}

Devcard3/DevCard_project2/Models/Contant.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCard_project2.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(3, ErrorMessage = "حداقل طول نام، 3 کاراکتر است")]
        [MaxLength(100, ErrorMessage = "حداکثر طول نام، 100 کاراکتر است")]
        public string Name { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری است")]
        [EmailAddress(ErrorMessage = "مقدار وارد شده ایمیل صحیح نیست")]
        public string Email { get; set; }

        public int Service { get; set; }
        public string Message { get; set; }
        public SelectList Services { get; set; }
       // public string service { get; set; }
    }
}

Devcard3/DevCard_project2/Models/ErrorViewModel.cs
namespace DevCard_project2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Devcard3/DevCard_project2/Models/IndexModel.cs
namespace DevCard_project2.Models;

public class IndexModel
{
    public List<Project2> Projects { get; set; }
    public List<Article> Articles { get; set; }

}

Devcard3/DevCard_project2/Models/Project2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NuGet.Protocol.Core.Types;

namespace DevCard_project2.Models
{
    public class Project2
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Client { get; set; }

        public Project2(long id, string name, string description,string image,
            string client)
        {
            Id = id;
            Name = name;
            Description = description;
            Image = image;
            Client = client;
        }
    }
}

Devcard3/DevCard_project2/Controllers/HomeController.cs
using DevCard_project2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DevCard_project2.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]

        public IActionResult Contact()
        {
            var model = new Contact();
            return View(model);
        }

        //[HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{
        //    var name = form["name"];
        //    return Json(Ok());
        //}
        // مدل بایدینگ
        [HttpPost]
        public JsonResult Contact(Contact form)
        {
            Console.WriteLine(form.ToString());
            return Json(Ok());
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public JavascriptResult Test2()
        {
            return new JavascriptResult("alert('سلام احمد رحیمی هستم') ");
        }

        public RedirectResult Index2()
        {
            return Redirect("http://www.baran-company.ir");

        }

        public RedirectToActionResult index3()
        {
            return RedirectToAction("Contact", "Home");
        }

        public IActionResult index4()
        {
            //return new OkResult();
            // return new NotFoundResult();
            //  return new BadRequestResult();
            return new NoContentResult();

        }
    }

    public class JavascriptResult : ContentResult
    {
        public JavascriptResult(string data)
        {
            Content = data;
            ContentType = "application/javascript";
        }
    }

}

Devcard3/DevCard_project2/ViewComponents/LatestArticlesViewComponent.cs
using DevCard_project2.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_project2.ViewComponents 
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var articles = new List<Article>
            {
                new Article(1,"پروژه انبار"," دانشگاه مازندران","blog-post-thumb-card-1.jpg"),
                new Article(1,"پروژه حسابداری"," وروشه","blog-post-thumb-card-2.jpg"),
                new Article(1,"پروژه فروش"," آکووین","blog-post-thumb-card-3.jpg"),
                new Article(1,"پروژه بازاریابی"," آپاستیک","blog-post-thumb-card-4.jpg"),


            };
            return View("_LatestArticles", articles);
        }
    }
}

Devcard3/DevCard_project2/ViewComponents/ProjectsViewComponent.cs
using System.Collections.Generic;
using DevCard_project2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace DevCard_project2.ViewComponents
{
    public class ProjectsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
           
            var projects = new List<Project2 >
            {
              new  Project2 (id:1,name:"علی",description:" برنامه نویس و عضو هیات مدیره علی  ","project-1.jpg",client:"برنامه نویس و عضو هیات مدیره1"),
              new  Project2 (id:2,name:"نیما",description:"نیما برنامه نویس و عضو هیات مدیره ","project-2.jpg",client:"برنامه نویس و عضو هیات مدیره2"),
              new  Project2 (id:3,name:"میلاد",description:"برنامه نویس و عضو هیات مدیره میلاد ","project-3.jpg",client:"برنامه نویس و عضو هیات مدیره3"),
              new  Project2 (id:4,name:"آصف",description:"آصف برنامه نویس و عضو هیات مدیره ","project-4.jpg", client:"برنامه نویس و عضو هیات مدیره4"),

            };
            return View("_Projects",projects);
        }

    }
}

Devcard3/DevCard_project2/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AppName</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AppName</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Devcard3/DevCard_project2/Views/Home/Components/LatestArticles/_LatestArticles.cshtml
@model List<Article>

<section class="latest-blog-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
        <div class="row">
            @foreach (var article in Model)
            {
                <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="~/assets/images/blog/@article.Image" alt="@article.Title" title="@article.Description">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="blog-post.html">
                                    @article.Title
                                </a>
                            </h5>
                            <p class="card-text">
                              @article.Description 
                            </p>
                            <p class="mb-0">
                                <a class="more-link" href="#">ادامه مطلب</a>
                            </p>

                        </div>
                    </div>
                </div>
            }

            


        </div>
    </div>
</section>

Devcard3/DevCard_project2/Views/Home/Components/Projects/_Projects.cshtml
@model IEnumerable<DevCard_project2.Models.Project2>

<section class="featured-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5">خاص ترین  همکاران</h2>
        <div class="row">
            @foreach (var project in Model)
            {
            <div class="col-md-6 mb-5">
                <div class="card project-card">
                    <div class="row no-gutters">
                        <div class="col-lg-4 card-img-holder">
                            <img src="~/assets/images/project/@project.Image" class="card-img" alt="image">
                        </div>
                        <div class="col-lg-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="project.html" class="theme-link">
                                       @project.Id : @project.Name
                                    </a>
                                </h5>
                                <p class="card-text">
                                    @*هسته فناور باران در واقع یک شرکت دانش بنیان می باشد.*@
                                    @project.Description
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">استاد: @project.Client</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            }
            
            
        </div>
    </div>
</section>

Devcard3/DevCard_project2/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "ارتباط با ما";
}

<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
        <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید.
            </p>
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">

        @if (!string.IsNullOrWhiteSpace(ViewBag.success))
        {
            <div class="alert-success p-5">
                <p>@ViewBag.success</p>
            </div>
        }

        @if (!string.IsNullOrWhiteSpace(ViewBag.error))
        {
            <div class="alert-danger p-5">
                <p>@ViewBag.error</p>
            </div>
        }

        <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام" >
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل" />
                          
                    <span asp-validation-for="Email" class="text-danger"></span>
                       
                </div>
                <div class="form-group col-12">
                    <select  class="custom-select" asp-for="Service">
                        <option value="0" selected="selected">سرویس مورد نظر خود را انتخاب کنید...</option>
                        <option value="basic"> نقره ای</option>
                        <option value="standard"> طلایی</option>
                        <option value="premium"> پلاتین</option>
                        <option value=" not sure"> الماس</option>

                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="sr-only" for="Message">پیغام شما</label>
                    <textarea class="form-control" asp-for="Message"
                              placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>

Devcard3/DevCard_project2/Views/Home/Index.cshtml
@*@model IndexModel*@
@{
    ViewData["Title"] = "صفحه اصلی";
}


<section class="about-me-section p-3 p-lg-5 theme-bg-light">
    <div class="container">
        <div class="profile-teaser media flex-column flex-lg-row">
            <img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="~/assets/images/Ahmad3.jpg" alt="">
            <div class="media-body">
                <h2 class="name font-weight-bold mb-1"> احمد رحیمی</h2>
                <div class="tagline mb-3">تحلیل گر ارشد</div>
                <div class="bio mb-4">
                    تحلیل ساخته شده است از یافتن یوزکیس ها و اکتور های سیستم
                    و سپس ساختن یوزکیس دیاگرام که در واقع ارتباط دهنده بین اکتورها و یوزکیس ها می باشد
                    و در نهایت طراحی دیاگرام های دیگه از جمله کلاس دیاگرام ,سیکوانس دیاگرام کولبوریشن دیاگرام . ...
                </div>
                <div class="mb-4">
                    <a class="btn btn-primary mr-2 mb-3" href="http://www.Baran-company.ir">
                        <i
                            class="fas fa-arrow-alt-circle-right ml-2">
                        </i>
                        <span class="d-none d-md-inline">
                            برو
                            به
                        </span> هسته فناور باران
                    </a>
                    <a class="btn btn-secondary mb-3" href="#">
                        <i class="fas fa-file-alt ml-2"></i>
                        <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>
@*<partial name="Projects"/>*@
@*@await Html.PartialAsync(partialViewName:"Projects", new List<Project>() )
*@
@await  Component.InvokeAsync(name:"Projects")

<div class="container">
    <hr>
</div>

@await Component.InvokeAsync("LatestArticles")

Devcard3/DevCard_project2/Views/Shared/Footer.cshtml
<footer class="footer text-center py-4">
    <small class="copyright">تولید شده توسط &copy; <a href="http://www.baran-company.ir" target="_blank"> هسته فناور
        باران</a></small>
</footer>

Devcard3/DevCard_project2/Views/Shared/Header.cshtml
<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">احمد رحیمی دنجکلائی</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="assets/images/Ahmad3.jpg" alt="image">

                    <div class="bio mb-3">سلام، احمد رحیمی دنجکلایی هستم مدیر عامل هسته فناور باران. به وبسایت شخصی من خوش
                        آمدید.</div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Home")"><i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی<span
                                                                                                                   class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact"><i
                                                                      class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما</a>
                    </li>
                </ul>
            </div>
		
        </nav>
    </div>
</header>

Devcard3/DevCard_project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <title>هسته فناور باران</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">

    <script defer src="~/assets/fontawesome/js/all.js"></script>

    <link rel="stylesheet" href="~/assets/css/theme-1.css">
    <link rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>

<partial name="Header"/>

<div class="main-wrapper">

    @RenderBody()


    <partial name="Footer"/>


</div>

<!-- Javascript -->
<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
<script src="~/assets/plugins/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<!--<script type="text/javascript" src="@Url.Action("Test2", "Home")"></script>-->

</body>

</html>